apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: prac-pod
  name: prac-pod
spec:
  containers:
  - image: nginx
    name: prac-pod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
